#!/usr/bin/env ruby

LIB_PATH = File.dirname(__FILE__) + "/lib/lichaam/"
require LIB_PATH

orgaansysteem = Lichaam::Orgaansysteem.new

hart = orgaansysteem.hart

3.times { hart.rechter_boezem.bloeddruk << Lichaam::Bloed.new }

puts
puts "Rechterboezem: " + hart.rechter_boezem.bloeddruk.to_s
puts "Rechterkamer: " + hart.rechter_kamer.bloeddruk.to_s

puts
puts "-- Diastole uitgevoerd"
hart.diastole

puts
puts "Rechterboezem: " + hart.rechter_boezem.bloeddruk.to_s
puts "Rechterkamer: " + hart.rechter_kamer.bloeddruk.to_s

puts
puts "-- Systole uitgevoerd"
hart.systole

puts
puts "Rechterboezem: " + hart.rechter_boezem.bloeddruk.to_s
puts "Rechterkamer: " + hart.rechter_kamer.bloeddruk.to_s
puts "Longslagader (#{hart.rechter_kamer.opvolger.class}): " + hart.rechter_kamer.opvolger.bloeddruk.to_s